name: Validate Home Assistant metadata

on:
  push:
  pull_request:
  workflow_dispatch:

permissions: {}

jobs:
  hassfest:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: home-assistant/actions/hassfest@a7c616ce81ccda50150bf1595786c71b1883fabb
